name: triforge_infotech
description: Triforge Infotech - Next Gen IT Company Website
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get:
  provider: ^6.1.2
  
  # Animations
  animate_do: ^3.3.4
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  
  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  
  # URL & Contact
  url_launcher: ^6.3.0
  
  # Utilities
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#    - assets/animations/
